name = "caveful_games/slick"
version = "3.0.0-rc.4"
description = "[Fork] slick is a simple to use polygon collision library inspired by bump.lua"
authors = ["erinmaus (https://github.com/erinmaus)", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/slick-luau"
license = "MPL-2.0"
private = true
includes = ["slick/**", "LICENSE", "README.md", "pesde.toml", "luau/**", ".luaurc"]

[target]
environment = "lune"
lib = "luau/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.7.0-rc.1"

[dev_dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.7" }
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.29" }
